### ISSUE TITLE
Where can i find database for this code ?

### ISSUE THREAD

**Issue by shayazm** [podio/asp-net-sample#1]
# Error : Could not connect to database A network related instance occured.
![image](https://cloud.githubusercontent.com/assets/24910527/21634437/27d9ee94-d20c-11e6-917c-9a80999be82c.png)

**Comment by shayazm** [comment]
@AjmalVh Please look into it...

**Comment by shayazm** [comment]
@RSpace

**Comment by RSpace** [comment]
Been a long time since I did this, but I'm pretty sure you just need to create local database called `PodioAspnetSampleDb` with a table called `PodioOAuthData`. The table should have the columns         `UserId` (integer) and `OAuthJsonData` (text). 

See this for more info on how the ORM works:
https://github.com/schotime/NPoco/wiki/Mapping

**Comment by shayazm** [comment]
Thanx alot Master it worked ! Also i am not able to get Space ID ,how can i get it ?

**Comment by AjmalVh** [comment]
Go to an item in the app. Click actions menu on the top, click on Developer info. You can see the space Id there. Here are some screenshots.
![2017-01-05_14-54-06](https://cloud.githubusercontent.com/assets/1432316/21676105/6dae30c0-d35a-11e6-871c-dd1c3c4baf73.jpg)
![2017-01-05_14-55-00](https://cloud.githubusercontent.com/assets/1432316/21676104/6dae3e3a-d35a-11e6-8f97-7aae58ed2d23.jpg)

**Comment by shayazm** [comment]
thanx alot it was helpfull !
